language: scala
scala:
- 2.11.11
- 2.12.8
jdk:
- openjdk8
before_install:
- git fetch --tags
stages:
- name: test
- name: release
  if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
  # run ci-release only if previous stages passed
  - stage: release
    script: sbt ci-release

before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- rm -fv $HOME/.ivy2/.sbt.ivy.lock
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
